[package]
name = "simple_cli_test"
version = "0.2.0"
edition = "2021"


publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["rlib", "dylib"]


[dependencies]
bevy = { version = "0.13", default_features = false }
bevy_dexterous_developer = { path = "../../../bevy_dexterous_developer" }

[package.metadata]
hot_reload_features = ["bevy/dynamic_linking", "bevy/embedded_watcher", "bevy_dexterous_developer/hot_internal"]