[dependencies]
bevy = "0.12"
serde = "*"

[dependencies.dexterous_developer]
path = "../dexterous_developer"

[features]
orange = []

[lib]
crate-type = ["dylib", "rlib"]
name = "lib_dexterous_developer_example"
path = "src/lib.rs"

[package]
edition = "2021"
name = "dexterous_developer_example"
version = "0.1.0"

[workspace]
