[package]
name = "dexterous_developer_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "lib_dexterous_developer_example"
path = "src/lib.rs"
crate-type = ["rlib", "dylib"]

[features]
default = ["bevy"]
hot = ["dexterous_developer/hot"]
bevy = ["dep:bevy"]

[dependencies]

bevy = { version = "0.11", optional = true }
bevy-inspector-egui = "*"
dexterous_developer = { path = "../dexterous_developer" }
serde = "*"
