[workspace]
resolver = "2"
members = [
    "dexterous_developer_macros",
    "dexterous_developer",
    "dexterous_developer_cli",
    "dexterous_developer_example",
    "no_cli_launcher",
    "tools/ci",
]

exclude = ["testing/*"]
