[package]
name = "dexterous_developer"
version = "0.0.7"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "../README.md"
categories = ["games", "game-development"]
keywords = ["bevy"]
exclude = ["assets/**/*", "tools/**/*", ".github/**/*"]
authors = ["Lee-Orr"]
homepage = "https://lee-orr.github.io/dexterous_developer/"
repository = "https://github.com/lee-orr/dexterous_developer"
documentation = "https://lee-orr.github.io/dexterous_developer/"
description = "a hot-reload library for bevy"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["bevy"]
hot = ["dep:libloading", "dep:uuid", "dep:cargo", "dep:notify", "dep:debounce"]
hot_internal = [
    "dexterous_developer_macros/hot_internal",
    "dep:libloading",
    "dep:uuid",
]
bevy = ["dep:bevy", "dep:serde", "dep:rmp-serde"]
cli = ["hot"]


[dependencies]
anyhow = { version = "1" }
dexterous_developer_macros = { path = "../dexterous_developer_macros", version = "0.0.7" }
bevy = { version = "0.11", default-features = false, features = [
    "bevy_winit",
    "serialize",
], optional = true }
libloading = { version = "0.8", optional = true }
uuid = { version = "1", features = ["v4"], optional = true }
serde = { version = "1", optional = true }
rmp-serde = { version = "1", optional = true }
cargo = { version = "0.72", optional = true }
notify = { version = "6", optional = true }
debounce = { version = "0.2", optional = true }
